### ISSUE TITLE
Reduce Dependencies

### ISSUE THREAD

**Issue by gmogames** [Privo/privo3-ios-sdk#17]
Hi there,

I was wondering if KeychainAccess is really a needed dependency as it's used in a single place for a simple read/write operation?
Cant this be replaced by a native keychain implementation to avoid adding extra dependencies?

I know it's a simple library and you don't have many dependencies, but when added to our project, that already requires quite a few dependencies, the lesser the better.

Thank you

**Comment by AlexSlo-Dev** [comment]
Hello again. Please update to version 0.0.7. We introduced a new PrivoKeychain implementation and delete dependency on KeychainAccess. Thank you for your feedback and code!
